### ISSUE TITLE
Wrong vagrant box in 3.1 quickstart?

### ISSUE THREAD

**Issue by j-warchol** [cloudify-cosmo/getcloudify.org#134]
It seems that in `guide/3.1/quickstart.md` there is a link to a Vagrant box with an old version of Cloudify (3.0) - see variable definitions on top of https://github.com/cloudify-cosmo/getcloudify.org/blob/master/guide/3.1/quickstart.md

(I hope that this is the right place to report it - there was no information about opening issues in README.  I would submit a pull request if i knew where the correct box is - didn't find it on Amazon.)

**Comment by m1keil** [comment]
Thank you for the report. This issue was fixed a while ago but we haven't updated this here. Sorry about that!
