### ISSUE TITLE
Add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [cloudify-cosmo/getcloudify.org#286]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms you're providing it, and under what license you expect the contributions to be? Thanks!

FYI, here's what [GitHub says on copyright and licenses](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> **What happens if I don't choose a license?**
>
> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.
>
> Even if this is what you intend, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository.
>
> If you want to share your work with others, we strongly encourage you to include an open source license.

**Comment by uric** [comment]
@mbrukman thanks for pointing that out. We will add a license file shortly.

**Comment by uric** [comment]
@mbrukman we've added a license, creative commons Attribution-NonCommercial-ShareAlike 4.0. Hope this clarifies this.

**Comment by mbrukman** [comment]
Thanks, @uric! Much appreciated.
